spring:
  application:
    name: SERVER-CONFIG-FILE-WORKING-DEV-PROFILE
server:
  port: 9100
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
