spring:
  application:
    name: SERVER-CONFIG-FILE-WORKING-NO-PROFILE
profiles:
  active: prod
server:
  port: 9100
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
